version: '3.8'

services:
  app:
    build:
      context: .
    command: bash start-dev.sh
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      GRADLE_USER_HOME: /box
      SPRING_PROFILES_ACTIVE: dev
    volumes:
      - .:/reactive-flashcards
      - box:/box
    depends_on:
      - db
    networks:
      - reactive-net

  db:
    image: mongo:7.0.9
    environment:
      MONGO_INITDB_ROOT_USERNAME: reactive-flashcards
      MONGO_INITDB_ROOT_PASSWORD: reactive-flashcards
      MONGO_INITDB_DATABASE: reactive-flashcards
    ports:
      - "27017:27017"
    networks:
      - reactive-net

  box:
    image: busybox
    volumes:
      - /box
    networks:
      - reactive-net

  mailcatcher:
    image: dockage/mailcatcher:0.9
    ports:
      - "1025:1025"
      - "1080:1080"
    networks:
      - reactive-net

volumes:
  db:
  box:

networks:
  reactive-net:
    name: custom-net
